[package]
name = "nbrs_no4"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nonebot_rs = { path = "../nonebot_rs", features = ["matcher"] }
nbrs_matcher_r6s = { path = "../nbrs_matcher_r6s" }
